accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<str:username>/', views.detail, name='detail'),
]

movie/urls.py
from django.urls import path

urlpatterns = []

recommendator/urls.py
from django.contrib import admin
from django.urls import path, include
# from movie import urls
# from administor import urls
# from accounts import urls
from rest_api import urls
import rest_api
from rest_framework_swagger.views import get_swagger_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', rest_api.views.main, name="home"),
    path('administor/', rest_api.views.administor, name="administor"),
    path('movie/', include('movie.urls')),
    path('accounts/',include('accounts.urls')),
    path('api/v1/', include('rest_api.urls')),
    path('docs/', get_swagger_view(title="Movie Recommend App : API Document")),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!--Axios-->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <!--Vue-->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!--BASE_URL Setting-->
    <script>
        const BASE_URL = 'movie-recommend-app-naye0ng.c9users.io'
    </script>
    <title>Document</title>
</head>
<body>
    {% include 'nav.html' %}
    
    {% block body %}
    {% endblock %}
    
</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg">
  <div class="row navbar-menu">
    <a href="{% url 'home' %}"><div class='navbar-btn'><i class="fas fa-home"></i></div></a>
    {% if user.username %}
      <a href="{% url 'accounts:detail' user.username %}"><div class='navbar-btn'>
        <i class="fas fa-user"></i>[{{ user.username }}]
      </div></a>
      {% if user.isAdmin %}
      <!--관리자/두개 토글할 것!-->
      <a href="{% url 'administor' %}"><div class='navbar-btn'>관리자</div></a>
      {% endif %}
      <a href="{% url 'accounts:logout' %}"><div class='navbar-btn'>로그아웃</div></a>
    {% else %}
    <a href="{% url 'accounts:login' %}"><div class='navbar-btn'>로그인</div></a>
    <a href="{% url 'accounts:signup' %}"><div class='navbar-btn'>회원가입</div></a>
    {% endif %}
    

 </div>
</nav>